import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  body: {backgroundColor: '#fff', flex: 1},
  storesView: {
    backgroundColor: '#1C7584',
    width: '100%',
    height: 200,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  storesViewText1: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  storesViewText2: {
    color: '#fff',
    fontSize: 13,
    textAlign: 'left',
    paddingBottom: 20,
  },
  storeImg: {
    position: 'absolute',
    width: 144,
    height: 146,
    right: 30,
    top: 120,
  },
  heytext: {
    color: '#000',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'left',
    marginTop: 20,
    marginLeft: 20,
  },
  heyView: {
    marginTop: 20,
    height: 210,
    width: '100%',
    alignItems: 'center',
  },
  catimg: {
    width: 61,
    height: 48,
    alignSelf: 'center',
  },
  cattext: {
    fontSize: 14,
    fontWeight: '500',
    marginTop: 5,
  },
  catView: {
    margin: 5,
    width: 96,
    height: 102,
    justifyContent: 'center',
  },
  optnimg: {
    width: 25,
    height: 25,
    alignSelf: 'center',
  },
  optntext: {
    fontSize: 12,
    fontWeight: '500',
    marginTop: 5,
  },
  optnView: {
    marginTop: 70,
    height: 70,
    width: 80,
    justifyContent: 'center',
  },
  faddimg: {
    width: 99,
    height: 55,
  },
  faddView: {
    marginHorizontal: 20,
    flexDirection: 'row',
    top: 30,
  },
  faddtext1: {
    color: 'black',
    fontWeight: '500',
    fontSize: 18,
    marginTop: 5,
    marginLeft: 15,
  },
  faddtext2: {color: '#A0A0A0', fontSize: 13, marginLeft: -109, marginTop: 15},
  poputext: {
    color: '#000',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'left',
    marginTop: 50,
    marginLeft: 20,
  },
  restrtimg: {
    width: 180,
    height: 140,
    borderRadius: 10,
  },
  restrtclock: {
    width: 16,
    height: 16,
  },
  restrttext: {
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'left',
    marginTop: 5,
  },
  restrtView: {
    marginTop: 20,
    marginLeft: 10,
    alignItems: 'flex-start',
  },
  restrttime: {
    color: 'black',
    fontSize: 12,
    marginLeft: 5,
  },
  offerimg: {
    width: 300,
    height: 200,
    borderRadius: 10,
  },
  offerView: {
    marginTop: 20,
    marginBottom: 20,
    marginLeft: 10,
    height: 200,
    width: 300,
    justifyContent: 'center',
  },
  row: {flexDirection: 'row'},
  active: {
    backgroundColor: '#1C7584',
    height: 4,
    marginLeft: -2,
    width: '105%',
  },
  t1: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 17,
    paddingTop: 20,
  },
  downView1: {
    alignItems: 'center',
    height: 55,
    flexDirection: 'row',
    marginHorizontal: 20,
    borderRadius: 50,
    justifyContent: 'space-between',
    backgroundColor: '#FFf',
  },
  eyeBtn1: {
    textAlign: 'center',
    textAlignVertical: 'center',
    marginRight: 0,
  },
  RecSearch: {
    color: 'grey',
    margin: 5,
    borderWidth: 0.5,
    width: '22%',
    fontSize: 12,
    padding: 10,
    textAlign: 'center',
    borderRadius: 20,
    borderColor: '#0000000D',
    backgroundColor: '#0000000D',
  },
  menulist: {
    width: '95%',
    marginLeft: 20,
    marginTop: 10,
  },
  menulist2: {
    marginTop: 2,
    marginHorizontal: 10,
  },
  menutext: {
    color: '#1C7584',
    fontWeight: '500',
    fontSize: 15,
    marginRight: 5,
    textAlign: 'center',
    paddingBottom: 5,
  },
  meenu: {flexWrap: 'wrap', flexDirection: 'row', marginHorizontal: 10},
});

export default styles;
