export default {
    
    //Logo
    Logo: require('./Images/LOGO.png'),

    //Auth Icons
    OnBoard: require("./Images/Onboard.png"),
    OnBoard1: require("./Images/onBoard1.png"),
    OnBoard2: require("./Images/Onboard2.png"),
    ArrowRight: require('./Images/ArrowRight.png'),
    location: require('./Images/Location.png'),
    locationMap: require('./Images/Location1.png'),
    Search: require('./Images/Search.png'),
    BackIcon: require('./Images/back.png'),
    Check: require('./Images/check.png'),
    // Social Icons
    Google: require('./Images/google.png'),
    Facebook: require('./Images/facebook.png'),
    Email: require('./Images/email.png'),

    //Home
    search: require('./Images/Searchh.png'),
    Profile: require('./Images/Profile.png'),
    Menu: require('./Images/menu.png'),
    Fav: require('./Images/Fav.png'),
    Share: require('./Images/share.png'),
    Store: require('./Images/Vector.png'),
    FDS: require('./Images/FDS.png'),
    Give: require('./Images/give.png'),
    Past: require('./Images/past.png'),
    Game: require('./Images/game.png'),
    Super: require('./Images/super.png'),
    Allo: require('./Images/img1.png'),
    Barbar: require('./Images/img2.png'),
    Sandwich: require('./Images/img.png'),
    Offer1: require('./Images/img3.png'),
    Offer2: require('./Images/img4.png'),
    Offer3: require('./Images/img5.png'),

    //Category
    Fast: require('./Images/fastfood.png'),
    Gift: require('./Images/gift.png'),
    Pharm: require('./Images/pharmacy.png'),
    Flowers: require('./Images/flowers.png'),
    Electronic: require('./Images/electronics.png'),
    Grocery: require('./Images/grocery.png'),

    //HomeDetail
    Filter: require('./Images/Filter.png'),
    Cook: require('./Images/cook.png'),
    Mark: require('./Images/mark.png'),
    Star:require('./Images/Star.png'),
    Pick: require('./Images/img6.png'),
    Pick1: require('./Images/img7.png'),
    Discount: require('./Images/discount.png'),
    Texes: require('./Images/Image.png'),
    Hut: require('./Images/Image3.png'),
    Paracon: require('./Images/Image2.png'),
    HotGrill: require('./Images/Image1.png'),
    Price: require('./Images/price.png'),

    //restaurant details
    Info: require('./Images/info.png'),
    Meenu: require('./Images/meenu.png'),
    Item: require('./Images/item.png'),
    Item2: require('./Images/item2.png'),
    Item3: require('./Images/item3.png'),
    Item4: require('./Images/item4.png'),
    Item5: require('./Images/item5.png'),
    Item6: require('./Images/item6.png'),
    Item7: require('./Images/item7.png'),
    Item1: require('./Images/item1.png'),
    Note: require('./Images/note.png'),
    Cutlery: require('./Images/cutlery.png'),
    Locate: require('./Images/Locate.png'),
    Locate1: require('./Images/Locate1.png'),
    Locate2: require('./Images/Locate2.png'),
    Bike: require('./Images/bike.png'),
    Pizza: require('./Images/Pizza.png'),

    //Settings
    Pic: require('./Images/pic.png'),
    UAE: require('./Images/uae.png'),
    Order: require('./Images/set1.png'),
    Offer:  require('./Images/set2.png'),
    Bell:  require('./Images/set3.png'),
    pay:  require('./Images/set4.png'),
    Heart: require('./Images/Heart.png'),
    Heartfill: require('./Images/heart1.png'),
    Help: require('./Images/set5.png'),
    About: require('./Images/set6.png'),
    Offr: require('./Images/offer.png'),
    Offr1: require('./Images/offer1.png'),
    Offr2: require('./Images/offer2.png'),
    notif: require('./Images/notif.png'),
    Cardlogo: require('./Images/card.png'),
    CardStar: require('./Images/softstar.png'),
    CardStar1: require('./Images/softstar1.png'),
    Chip: require('./Images/chips.png'),
    
}