import {StyleSheet} from 'react-native';
import {heightRef} from 'src/config/screenSize';

const styles = StyleSheet.create({
  bgimg: {
    width: '100%',
    height: 220 * heightRef,
  },
  line: {
    backgroundColor: '#A0A0A0',
    height: 0.5,
    width: '100%',
    marginVertical: 20,
  },
  view1: {flexDirection: 'row'},
  oshatext: {color: 'black', fontSize: 18, fontWeight: '500'},
  radioText: {color: 'black', fontSize: 18, fontWeight: '500', marginLeft: 10},
  oshatext1: {color: 'black', fontSize: 16, fontWeight: '500'},
  oshatextv: {color: 'black', fontSize: 14, fontWeight: '500'},
  oshatextm: {
    color: 'black',
    fontSize: 12,
    fontWeight: '500',
    marginVertical: 5,
  },
  oshatextc: {color: 'black', fontSize: 16, fontWeight: '500', marginLeft: 5},
  infotext: {color: 'green', fontSize: 14},
  emitext: {color: '#A0A0A0', marginVertical: 3, fontSize: 12},
  ratingtextview: {flexDirection: 'row', justifyContent: 'space-between'},
  ratingtext: {color: '#A0A0A0', fontSize: 14, marginLeft: 5},
  revtext: {
    color: '#EF5DA8',
    fontWeight: '500',
    fontSize: 14,
    marginVertical: 14,
  },
  revtextpm: {
    color: '#E0281C',
    fontSize: 25,
    textAlign: 'right',
  },
  revtextpmm: {
    color: '#A0A0A0',
    fontSize: 25,
    textAlign: 'center',
  },
  revtextpmc: {
    color: '#000',
    fontSize: 20,
    marginTop: 3,
    paddingHorizontal: 20,
  },
  clockicon: {height: 25, width: 25},
  textplay: {color: 'black', fontSize: 18, fontWeight: '500'},
  textanyT: {color: '#000', fontSize: 14, marginTop: 10, fontWeight: 'bold'},
  textany: {color: '#000', fontSize: 14, marginTop: 10},
  textany2: {color: '#000', fontSize: 16, marginTop: 10},
  emark: {height: 25, width: 25, left: 95, top: 8},
  deltext: {
    color: '#A0A0A0',
    fontSize: 12,
    marginLeft: 40,
    marginTop: -15,
  },
  deltext1: {color: '#A0A0A0', fontSize: 14, marginTop: 0.5},
  deltext2: {color: '#E0281C', fontSize: 14},
  deltextnextT: {
    color: '#000',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 10,
  },
  deltextnext: {color: '#000', fontSize: 14, marginTop: 10},
  deltext3: {
    flexDirection: 'column',
    color: '#000',
    fontSize: 14,
    marginVertical: 10,
  },
  offlist: {
    backgroundColor: '#EF5DA8',
    height: 80,
    width: 250,
    borderRadius: 10,
    justifyContent: 'center',
    flexDirection: 'row',
    marginRight: 10,
  },
  offimg: {tintColor: '#fff', height: 25, width: 25, left: 20, top: 25},
  adtext: {
    fontSize: 12,
    color: '#fff',
    paddingHorizontal: 30,
    marginTop: 25,
  },
  menuicon: {
    height: 15,
    width: 20,
    top: 20,
  },
  ystar: {
    height: 15,
    width: 15,
  },
  gstar: {
    tintColor: '#A0A0A0',
    height: 15,
    width: 15,
  },
  menulist: {
    width: '95%',
    marginLeft: 40,
  },
  menulist2: {
    marginTop: 2,
    marginHorizontal: 10,
  },
  menutext: {
    color: '#1C7584',
    fontWeight: '500',
    fontSize: 14,
    marginRight: 5,
    textAlign: 'center',
    paddingBottom: 5,
  },
  trendheading: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 20,
  },
  mainlistview: {flexDirection: 'row', marginVertical: 30},
  mlisttext: {
    color: 'black',
    fontWeight: '500',
    fontSize: 16,
  },
  mlistdes: {
    color: 'grey',
    fontSize: 10,
    paddingRight: 125,
  },
  mlistprice: {
    color: '#EF5DA8',
    fontSize: 10,
    top: 20,
  },
  mlistimg: {
    height: 92,
    width: 118,
    borderRadius: 10,
  },
  centeredView: {
    flex: 1,
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
    alignItems: 'center',
  },
  modalView: {
    backgroundColor: 'white',
    marginTop: 220,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  twoview: {
    backgroundColor: 'black',
    height: 20,
    width: 20,
    borderRadius: 15,
    marginTop: 2.5,
    borderColor: 'black',
    borderWidth: 1,
  },
  mapview: {
    marginBottom: 10,
    height: 180,
    width: '100%',
    borderRadius: 20,
    overflow: 'hidden',
  },
  check: {
    flexDirection: 'row',
    backgroundColor: '#fdf4f4',
    borderRadius: 10,
  },
  check2: {
    flexDirection: 'row',
    paddingVertical: 20,
    paddingHorizontal: 15,
    borderRadius: 10,
  },
  uncheck: {
    backgroundColor: '#1C75840D',
    padding: 20,
    borderRadius: 10,
    marginTop: 40,
  },
  btn: {
    flexDirection: 'row',
    marginTop: 130,
  },
});

export default styles;
